services:
  file_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_api_container
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
